version: '3.3'
services:
  redis:
    image: redis
    container_name: redisserver
    expose:
     - "6379"

  backend:
    build: ./plasma-core
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./plasma-core:/usr/src/app"
      - "./data/leveldb:/var/lib/leveldb/data"
      - "./data/logs/plasma-core:/usr/src/app/app/logs"
      - "./data/ethernode/geth_ipc:/usr/src/geth_ipc:ro"
    links: 
      - redis
    environment:
      REDIS_HOST: redisserver
      NODE_ENV: development
      LOG_LEVEL: "debug"
      PRODUCTION_MODE: "OFF"
      PLASMA_CONTRACT_ADDRESS: '0x751586e389d0cdaacd81af6bff07ddfdad5c816d'
      PLASMA_NODE_ADDRESS: '0x2bf64b0ebd7ba3e20c54ec9f439c53e87e9d0a70'
      PLASMA_NODE_PRIVATE: ''
      PLASMA_NODE_PASSWORD: '123123123'
      WEB3_HTTP_PROVIDER: ''
    command: 'npm run development'
    logging:
      options:
        max-size: 1000m
    restart: 'no'
